spring:
  application:
    name: "reactive"
  r2dbc:
    url: "r2dbc:h2:mem:///development"
    username: "sa"
    password: "password"
  flyway:
    enabled: true
    locations: "classpath:db/migration"